# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Indices
                                 A QGIS plugin
 NDVI (Normalized Difference Vegetation Index) is a widely used vegetation index that quantifies vegetation health and density based on the difference in reflectance between near-infrared (NIR) and red light bands of satellite or aerial imagery. Here's some information about an NDVI tool plugin:

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-10
        copyright            : (C) 2024 by J Tech
        email                : hj03110527984@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Indices class from file Indices.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Indice_calculater import Indices
    return Indices(iface)
