# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LatLangCac
                                 A QGIS plugin
 I am the decription 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-07
        copyright            : (C) 2024 by J Tech
        email                : sd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LatLangCac class from file LatLangCac.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .latlangcalc import LatLangCac
    return LatLangCac(iface)
